# Generated by Django 4.1.5 on 2023-01-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdetails',
            name='additional',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
