# Generated by Django 4.1.5 on 2023-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp1', '0003_alter_boxdetails_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxdetails',
            name='dcmio',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
